export const deviceData = [
  {
    id: 1,
    lebel: "Android Phone",
    img_src: "/images/android.png",
    models: [
      {
        id: 1,
        lebel: "Samsung",
        img_src: "/images/android.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "LG",
        img_src: "/images/a1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Google Pixel",
        img_src: "/images/device/1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "Motorola",
        img_src: "/images/device/2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 5,
        lebel: "Oneplus",
        img_src: "/images/device/3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 6,
        lebel: "HTC",
        img_src: "/images/device/4.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 7,
        lebel: "Huewai",
        img_src: "/images/device/5.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 8,
        lebel: "...Other",
        img_src: "/images/device/6.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    lebel: "Iphone",
    img_src: "/images/iphone.png",
    models: [
      {
        id: 1,
        lebel: "Iphone 15 Pro Max",
        img_src: "/images/ip1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "Iphone 15 Pro",
        img_src: "/images/ip2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Iphone 15 Plus",
        img_src: "/images/ip3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "Iphone 15",
        img_src: "/images/ip4.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 5,
        lebel: "Iphone 11 Pro",
        img_src: "/images/iphone/1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 6,
        lebel: "Iphone 12 Mini",
        img_src: "/images/iphone/2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 7,
        lebel: "Iphone XR",
        img_src: "/images/iphone/3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 8,
        lebel: "Iphone 8 Plus",
        img_src: "/images/iphone/4.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    lebel: "Tablet",
    img_src: "/images/tablet.png",
    models: [
      {
        id: 1,
        lebel: "iPad Pro 12.9 (5th Gen)",
        img_src: "/images/tab/1.jpeg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "iPad Pro 12.9 (4th Gen)",
        img_src: "/images/tab/2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "iPad Pro 12.9 (6th Gen)",
        img_src: "/images/tab/3.jpeg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "iPad Pro 12.9 (3rd Gen)",
        img_src: "/images/tab/4.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 5,
        lebel: "iPad Pro 11 (3rd Gen)",
        img_src: "/images/tab/5.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 6,
        lebel: "iPad Pro 11 (2nd Gen)",
        img_src: "/images/tab/6.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 7,
        lebel: "iPad 9th Gen",
        img_src: "/images/tab/7.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 8,
        lebel: "iPad 8th Gen",
        img_src: "/images/tab/8.jpeg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    lebel: "Computers",
    img_src: "/images/com.png",
    models: [
      {
        id: 1,
        lebel: "PC Laptop",
        img_src: "/images/com/1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "PC Desktop",
        img_src: "/images/com/2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Chromebook",
        img_src: "/images/com/3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "iMac",
        img_src: "/images/com/4.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 5,
        lebel: "MacBook",
        img_src: "/images/com/5.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    lebel: "Game Console Repair",
    img_src: "/images/game.png",
    models: [
      {
        id: 1,
        lebel: "XBox",
        img_src: "/images/game/1.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "Playstation",
        img_src: "/images/game/2.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Nintendo",
        img_src: "/images/game/1.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    lebel: "Apple Watch",
    img_src: "/images/watch.png",
    models: [
      {
        id: 1,
        lebel: "Apple Watch Series 7 45mm",
        img_src: "/images/watch/1.jpeg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "Apple Watch Series 7 41mm",
        img_src: "/images/watch/2.jpeg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Apple Watch Series 6 41mm",
        img_src: "/images/watch/3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "Apple Watch Series 6 44mm",
        img_src: "/images/watch/4.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 5,
        lebel: "Apple Watch Series 5 44mm",
        img_src: "/images/watch/5.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 6,
        lebel: "Apple Watch Series 5 40mm",
        img_src: "/images/watch/6.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 7,
        lebel: "Apple Watch Series 4 40mm",
        img_src: "/images/watch/7.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },

          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
];
