export const deviceData = [
  {
    id: 1,
    lebel: "Android Phone",
    img_src: "/images/android.png",
    models: [
      {
        id: 1,
        lebel: "Samsung",
        img_src: "/images/android.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "LG",
        img_src: "/images/a1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    lebel: "Iphone",
    img_src: "/images/iphone.png",
    models: [
      {
        id: 1,
        lebel: "Iphone 15 Pro Max",
        img_src: "/images/ip1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 2,
        lebel: "Iphone 15 Pro",
        img_src: "/images/ip1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 3,
        lebel: "Iphone 15 Plus",
        img_src: "/images/ip1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
      {
        id: 4,
        lebel: "Iphone 15",
        img_src: "/images/ip1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    lebel: "Tablet",
    img_src: "/images/tablet.png",
    models: [
      {
        id: 1,
        lebel: "iPad Pro 12.9 (5th Gen)",
        img_src: "/images/tab1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issue/1.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issue/2.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issue/3.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issue/4.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issue/5.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issue/6.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issue/7.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issue/8.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issue/9.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issue/10.png",
            timeframe: "60 minutes",
            warranty: "90 days Warranty",
          },
        ],
      },
    ],
  },
];
