export const widgetData = [
  {
    id: 1,
    lebel: "Smart Phones",
    img_src: "/images/android.png",
    models: [
      {
        id: 1,
        lebel: "Samsung",
        img_src: "/images/android.png",
        devices: [
          "Samsung Galaxy S24 Ultra",
          "Samsung Galaxy S24+",
          "Samsung Galaxy S24",
          "Samsung Galaxy S23 FE",
          "Samsung Galaxy Z Fold5",
          "Samsung Galaxy Z Flip5",
          "Samsung Galaxy S23 Ultra 5G",
          "Samsung Galaxy S23+ 5G",
          "Samsung Galaxy S23 5G",
          "Samsung Galaxy Z Flip4",
          "Samsung Galaxy Z Fold4",
          "Samsung Galaxy S22 Ultra 5G",
          "Samsung Galaxy S22+ 5G",
          "Samsung Galaxy S22 5G",
          "Samsung Galaxy Z Flip3 5G",
          "Samsung Galaxy Z Fold3 5G",
          "Samsung Galaxy S21 Ultra 5G",
          "Samsung Galaxy S21+ 5G",
          "Samsung Galaxy S21 5G",
          "Samsung Galaxy S21 FE 5G",
          "Samsung Galaxy Note 20 Ultra 5G",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 2,
        lebel: "Iphone",
        img_src: "/images/ip1.jpg",
        devices: [],

        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 3,
        lebel: "LG",
        img_src: "/images/device/1.jpg",
        devices: [],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 4,
        lebel: "Other",
        img_src: "/images/device/1.jpg",
        devices: [],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
    ],
  },
  {
    id: 2,
    lebel: "Tablets",
    img_src: "/images/tablet.png",
    models: [],
    issues: [
      { id: 1, lebel: "Screen" },
      { id: 2, lebel: "Back Glass" },
      { id: 3, lebel: "Front Camera" },
      { id: 4, lebel: "Back Camera" },
      { id: 5, lebel: "Charging Port" },
      { id: 6, lebel: "Speaker" },
      { id: 7, lebel: "Water Damage" },
      { id: 8, lebel: "Virus" },
      { id: 9, lebel: "Data Recovery" },
      { id: 10, lebel: "Overheats" },
      { id: 11, lebel: "Power Resets" },
    ],
  },
  {
    id: 3,
    lebel: "Computers",
    img_src: "/images/com.png",
    models: [
      {
        id: 1,
        lebel: "Desktops",
        img_src: "/images/com/2.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issues2/2.png",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issues2/3.png",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issues2/4.png",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
      {
        id: 2,
        lebel: "Laptops",
        img_src: "/images/com/1.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issues2/2.png",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issues2/3.png",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issues2/4.png",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
      {
        id: 3,
        lebel: "Mac",
        img_src: "/images/com/4.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issues2/2.png",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issues2/3.png",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issues2/4.png",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
      {
        id: 4,
        lebel: "Other Devices",
        img_src: "/images/com/3.jpg",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },
          {
            id: 2,
            lebel: "Back Glass",
            img_src: "/images/issues2/2.png",
          },
          {
            id: 3,
            lebel: "Front Camera",
            img_src: "/images/issues2/3.png",
          },
          {
            id: 4,
            lebel: "Back Camera",
            img_src: "/images/issues2/4.png",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    lebel: "Something else",
    img_src: "/images/game.png",
    models: [
      {
        id: 1,
        lebel: "Watch",
        img_src: "/images/watch.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },

          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
      {
        id: 2,
        lebel: "Playstation",
        img_src: "/images/game/2.png",
        issues: [
          {
            id: 1,
            lebel: "Screen",
            img_src: "/images/issues2/1.png",
          },
          {
            id: 5,
            lebel: "Charging Port",
            img_src: "/images/issues2/5.png",
          },
          {
            id: 6,
            lebel: "Speaker",
            img_src: "/images/issues2/6.png",
          },
          {
            id: 7,
            lebel: "Water Damage",
            img_src: "/images/issues2/8.png",
          },
          {
            id: 8,
            lebel: "Virus",
            img_src: "/images/issues2/7.png",
          },
          {
            id: 9,
            lebel: "Data Recovery",
            img_src: "/images/issues2/9.png",
          },
          {
            id: 10,
            lebel: "Overheats",
            img_src: "/images/issues2/10.png",
          },
          {
            id: 11,
            lebel: "Power Resets",
            img_src: "/images/issues2/11.png",
          },
        ],
      },
    ],
  },
];
