export const widgetData = [
  {
    id: 1,
    lebel: "Smart Phones",
    img_src: "/images/android.png",
    models: [
      {
        id: 1,
        lebel: "Samsung",

        devices: [
          "Samsung Galaxy S24 Ultra",
          "Samsung Galaxy S24+",
          "Samsung Galaxy S24",
          "Samsung Galaxy S23 FE",
          "Samsung Galaxy Z Fold5",
          "Samsung Galaxy Z Flip5",
          "Samsung Galaxy S23 Ultra 5G",
          "Samsung Galaxy S23+ 5G",
          "Samsung Galaxy S23 5G",
          "Samsung Galaxy Z Flip4",
          "Samsung Galaxy Z Fold4",
          "Samsung Galaxy S22 Ultra 5G",
          "Samsung Galaxy S22+ 5G",
          "Samsung Galaxy S22 5G",
          "Samsung Galaxy Z Flip3 5G",
          "Samsung Galaxy Z Fold3 5G",
          "Samsung Galaxy S21 Ultra 5G",
          "Samsung Galaxy S21+ 5G",
          "Samsung Galaxy S21 5G",
          "Samsung Galaxy S21 FE 5G",
          "Samsung Galaxy Note 20 Ultra 5G",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 2,
        lebel: "Iphone",

        devices: [
          "iPhone 15 Pro Max",
          "iPhone 15 Pro",
          "iPhone 15 Plus",
          "iPhone 15",
          "iPhone 14 Pro Max",
          "iPhone 14 Pro",
          "iPhone 14 Plus",
          "iPhone 14",
          "iPhone 13 Pro Max",
          "iPhone 13 Pro",
          "iPhone 13",
          "iPhone 13 Mini",
          "iPhone 12 Pro Max",
          "iPhone 12 Pro",
          "iPhone 12",
          "iPhone 12 Mini",
          "iPhone SE (3rd Gen)",
          "iPhone 11 Pro Max",
          "iPhone 11 Pro",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 3,
        lebel: "LG",

        devices: [
          "LG V60 ThinQ 5G",
          "LG Velvet 5G",
          "LG G8 ThinQ",
          "LG G7 ThinQ",
          "LG G7 One",
          "LG V50",
          "LG V40",
          "LG Q70",
          "LG G8X ThinQ",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 4,
        lebel: "Other",

        devices: [],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
    ],
  },
  {
    id: 2,
    lebel: "Tablets",
    img_src: "/images/tablet.png",
    models: [
      {
        id: 1,
        lebel: "IPad",
        devices: [
          "iPad Pro 12.9 (5th Gen)",
          "iPad Pro 11 (3rd Gen)",
          "iPad Air 5",
          "iPad 10.2 (9th Gen)",
          "iPad Air 4",
          "iPad 9.7 (6th Gen)",
          "iPad (5th Generation)",
          "iPad Air 3",
          "iPad Mini 6",
          "iPad Mini 5",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 2,
        lebel: "Google Tablet",
        devices: ["Nexus 10"],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
    ],
  },
  {
    id: 3,
    lebel: "Computers",
    img_src: "/images/com.png",
    models: [
      {
        id: 1,
        lebel: "Desktops",
        devices: [
          "Sony Computer",
          "Lenovo Computer",
          "HP Computer",
          "Dell Computer",
          "ASUS Computer",
          "Acer Computer",
          "Samsung Computer",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 2,
        lebel: "Laptops",
        devices: [
          "Samsung Chromebook 4",
          "Samsung Chromebook Plus",
          "Google Pixelbook Go",
        ],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 3,
        lebel: "Mac",
        devices: ["MacBook Pro", "MacBook", "MacBook Air", "iMac", "Mac Mini"],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 4,
        lebel: "Other Devices",
        devices: [],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
    ],
  },
  {
    id: 4,
    lebel: "Something else",
    img_src: "/images/game.png",
    models: [
      {
        id: 1,
        lebel: "Watch",
        devices: ["Apple watch", "Google watch"],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
      {
        id: 2,
        lebel: "Playstation",
        devices: ["Xbox Series X", "Xbox One", "XBOX 360 Slim", "XBOX 360"],
        issues: [
          { id: 1, lebel: "Screen" },
          { id: 2, lebel: "Back Glass" },
          { id: 3, lebel: "Front Camera" },
          { id: 4, lebel: "Back Camera" },
          { id: 5, lebel: "Charging Port" },
          { id: 6, lebel: "Speaker" },
          { id: 7, lebel: "Water Damage" },
          { id: 8, lebel: "Virus" },
          { id: 9, lebel: "Data Recovery" },
          { id: 10, lebel: "Overheats" },
          { id: 11, lebel: "Power Resets" },
        ],
      },
    ],
  },
];
